name: Terraform Apply

on:
  push:
    paths:
      - 'modules/**'
      - 'environments/dev/**'
      - '*.tf'
      - '.github/workflows/terraform.yml'

jobs:
  terraform:
    name: Terraform Apply (Dev)
    runs-on: ubuntu-latest

    env:
      TF_VAR_project_id: terraform-gcp-composer
      TF_VAR_region: europe-west2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: |
          cd environments/dev
          terraform init -backend-config="backend.tf"

      - name: Terraform Plan
        run: |
          cd environments/dev
          terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd environments/dev
          terraform apply -auto-approve -var-file="terraform.tfvars"
